### List events
GET http://localhost:3000/events

### Create event
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "",
  "description": "",
  "date": "",
  "price": -1
}

### Event Id
@eventId = 238bd872-3e3f-4542-94a0-b0cf3ba1e643

### List spots by event id
GET http://localhost:3000/events/{{eventId}}/spots

### Create spot by event id
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": ""
}

### Reserve spot by event id
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
  "spots": [],
  "ticket_kind": "",
  "email": "test$test.com"
}
