### List events
GET http://localhost:3000/events

### Create event
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "",
  "description": "",
  "date": "",
  "price": -1
}

### Event Id
@eventId = 4cc8e8f0-c79b-4de6-8580-c3c76b200ef8

### List spots by event id
GET http://localhost:3000/events/{{eventId}}/spots

### Create spot by event id
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": ""
}

### Reserve spot by event id
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
  "spots": [],
  "ticket_kind": "",
  "email": "test$test.com"
}

### Reserve spot by event id
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 123

{
  "spots": ["A1", "C3", "D5"],
  "ticket_kind": "full",
  "email": "test@test.com"
}
