services:
  app:
    build: .
    restart: on-failure:10
    command: >
      bash -c "npx prisma migrate dev && npm run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partner1
    ports:
      - 3306:3306
